/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'evente_mobile_admin_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String GILROY_BOLD = 'Gilroy-Bold';
  static const String GILROY_MEDIUM = 'Gilroy-Medium';
  static const String GILROY_REGULAR = 'Gilroy-Regular';
  static const String GILROY_SEMIBOLD = 'Gilroy-SemiBold';
}
